package com.moe365.mopi.processing;

import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.BiFunction;
import java.util.function.Consumer;

import au.edu.jcu.v4l4j.VideoFrame;

/**
 * An abstract image processor. This class is designed to allow easy
 * swapping of different image processing algorithms.
 * @author mailmindlin
 * @param <R> the result type generated by this processor
 * @since April 2017
 */
public abstract class AbstractParallelImageProcessor<R> implements ImageProcessor<R> {
	protected ExecutorService executor;
	
	protected BiFunction<VideoFrame, ByteBuffer, Callable<Pair<VideoFrame, ByteBuffer>> decoderFactory;
}
